### ISSUE TITLE
Running on latest version of Steam OS gives an error

### ISSUE THREAD

**Issue by acronmd** [popsUlfr/droidcam-steam-deck-appimage#1]
I tried running this on the latest stable version of Steam OS and it gives me the error "WARNING! No kernel module found that matches current kernel. The appimage may need to be updated."

**Comment by popsUlfr** [comment]
Hi, thank you for reminding me ;)

I've updated the appimage: https://github.com/popsUlfr/droidcam-steam-deck-appimage/releases/tag/v1.8.2-5.13.0-valve36-1-neptune
