### ISSUE TITLE
/lib/modules/6.1.52-valve16-1-neptune-61 issue

### ISSUE THREAD

**Issue by jammermt99** [popsUlfr/droidcam-steam-deck-appimage#4]
modprobe: FATAL: Module v4l2loopback-dc not found in directory /lib/modules/6.1.52-valve16-1-neptune-61
ERROR! Failed to load the needed modules.

How do I fix this?

**Comment by popsUlfr** [comment]
@jammermt99 I published a new release: https://github.com/popsUlfr/droidcam-steam-deck-appimage/releases/tag/v2.1.2-6.5.0-valve1-3-neptune-65-g3b047419df39
